---
# maven job for 'config' repo

- project:
    name: config
    project: '{name}'

    jobs:
      - 'config-gerrit':
          branch-regexp: '^(.*)$'

- job-group:
    name: 'config-gerrit'
    jobs:
      - 'verify-licensed'
      - 'maven-install'
      - 'maven-deploy'
