---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 The Linux Foundation

name: call-github2gerrit

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master
      - main

permissions:
  contents: read
  pull-requests: write
  issues: write

concurrency:
  # yamllint disable-line rule:line-length
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  submit-to-gerrit:
    runs-on: ubuntu-latest
    steps:
      - name: Submit PR to Gerrit
        id: g2g
        uses: lfreleng-actions/github2gerrit-action@main
        with:
          GERRIT_KNOWN_HOSTS: ${{ vars.GERRIT_KNOWN_HOSTS }}
          GERRIT_SSH_PRIVKEY_G2G: ${{ secrets.GERRIT_SSH_PRIVKEY_G2G }}
          GERRIT_SSH_USER_G2G: ${{ vars.GERRIT_SSH_USER_G2G }}
          GERRIT_SSH_USER_G2G_EMAIL: ${{ vars.GERRIT_SSH_USER_G2G_EMAIL }}
